version: "3.9"
name: "uat"
services:
  web:
    container_name: "base-native-uat"
    environment:
      - "SPRING_PROFILES_ACTIVE=uat"
    ports:
      - "8092:8080"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge